
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class TokenNames {
  /* terminals */
  public static final int TIMES = 7;
  public static final int RBRACK = 13;
  public static final int LT = 19;
  public static final int CLASS = 28;
  public static final int TYPE_STRING = 27;
  public static final int SEMICOLON = 16;
  public static final int PLUS = 5;
  public static final int INT = 32;
  public static final int RBRACE = 15;
  public static final int RPAREN = 11;
  public static final int WHILE = 8;
  public static final int TYPE_INT = 21;
  public static final int LBRACK = 12;
  public static final int RETURN = 24;
  public static final int ERROR = 30;
  public static final int IF = 2;
  public static final int NIL = 26;
  public static final int GT = 18;
  public static final int LPAREN = 10;
  public static final int LBRACE = 14;
  public static final int ID = 33;
  public static final int STRING = 29;
  public static final int COMMA = 20;
  public static final int EOF = 0;
  public static final int DIVIDE = 9;
  public static final int MINUS = 6;
  public static final int error = 1;
  public static final int DOT = 4;
  public static final int ASSIGN = 17;
  public static final int EQ = 3;
  public static final int NEW = 25;
  public static final int EXTENDS = 23;
  public static final int ARRAY = 22;
  public static final int TYPE_VOID = 31;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "EQ",
  "DOT",
  "PLUS",
  "MINUS",
  "TIMES",
  "WHILE",
  "DIVIDE",
  "LPAREN",
  "RPAREN",
  "LBRACK",
  "RBRACK",
  "LBRACE",
  "RBRACE",
  "SEMICOLON",
  "ASSIGN",
  "GT",
  "LT",
  "COMMA",
  "TYPE_INT",
  "ARRAY",
  "EXTENDS",
  "RETURN",
  "NEW",
  "NIL",
  "TYPE_STRING",
  "CLASS",
  "STRING",
  "ERROR",
  "TYPE_VOID",
  "INT",
  "ID"
  };
}

